## エラー画面
### 上部
```terminal
例外クラス: エラー内容 for 問題が起きたクラスのインスタンス
```
### バックトレース
番号が小さい程、エラーに近い新しい呼び出し、番号が大きい方から小さい方が呼び出され、最終的に番号がない行のエラーが起きている
```terminal
番号: from パス:行数:in 'エラーが起きたメソッド'
...
番号: from パス:行数:in 'エラーが起きたメソッド'
パス:行数:in 'エラーが起きたメソッド': 内容 for 問題が起きたインスタンス (例外クラス)
```

## デバッグ方法
- `printデバッグ` メソッドのスタート時点、変数の中身をprintする
  - `tapメソッド` レシーバーをそのままブロック引数に渡すメソッド、ブロック引数をprintする事で、メソッドの戻り値を確認できる
- `ログに出力` ログに目印を付けて、デバッグ情報を出力する
- `デバッガ` デバッグツールを使用する
- `irb` irbで実行してみる
- `ログの確認`
- `source_locationメソッド` ライブラリのコードの場所を返す
- `テストコードを書く` テストコード書いて、それをパスするコードを書き、徐々に書きたいコードに戻していく

## 例外クラス
- `NameError` 未定義のローカル変数や定数を使った時
  - タイプミス
  - requireのし忘れ
- `NoMethodError` 未定義のメソッドを呼び出そうとした時
  - タイプミス
  - レシーバーの型が想定と違った、nilになっている
- `TypeError` 期待しない型やクラスが、メソッドの引数に渡された時
  - 型変換のし忘れ
  - 整数と数字の足し算等をしている
- `ArgumentError` 引数の数が間違っている、期待している型ではない
  - 引数の型が想定と違った、nilになっている
- `SystemStackError` 無限ループが発生した等
- `LoadError` requireやloadの失敗
  - ファイル名のタイプミス、パスの勘違い
  - gemがインストールされていない
- `SyntaxError` 構文エラー
  - endや()の閉じ忘れ等
